import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'

const cfg={api:import.meta.env.VITE_SURELIN_API_URL,key:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}
const S={user:null,stats:{followers:0,following:0,friends:0},tab:'games',games:[],mine:[]}
const app=document.querySelector('#app')
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
async function api(path,opt={}){const token=localStorage.getItem('surelin_token');const r=await fetch(`${cfg.api}/${path}`,{...opt,headers:{'Content-Type':'application/json',apikey:cfg.key,...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function toast(t,good=false){const x=document.createElement('div');x.className='toast '+(good?'good':'');x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2600)}
const av=n=>`<span class="avatar">${esc((n||'?')[0].toUpperCase())}</span>`
function layout(content){app.innerHTML=`<header><button class="brand" data-tab="games"><i>S</i> surelin</button><nav><button data-tab="games" class="${S.tab==='games'?'on':''}">Games</button><button data-tab="mine" class="${S.tab==='mine'?'on':''}">Your Games</button>${S.user?`<button data-tab="friends" class="${S.tab==='friends'?'on':''}">Friends</button>`:''}${S.user?.is_admin?`<button data-tab="admin" class="${S.tab==='admin'?'on':''}">Admin</button>`:''}</nav><div class="right">${S.user?`<button class="profile" data-tab="profile">${av(S.user.username)} @${esc(S.user.username)}</button><button class="ghost" id="logout">Log out</button>`:`<button class="ghost" id="login">Log in</button><button class="primary small" id="signup">Create account</button>`}</div></header><main>${content}</main>`;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>openTab(x.dataset.tab));document.querySelector('#logout')?.addEventListener('click',()=>{localStorage.removeItem('surelin_token');S.user=null;openTab('games')});document.querySelector('#login')?.addEventListener('click',()=>auth(false));document.querySelector('#signup')?.addEventListener('click',()=>auth(true));document.querySelector('#newgame')?.addEventListener('click',()=>editor());document.querySelectorAll('[data-game]').forEach(x=>x.onclick=()=>editor(x.dataset.game));document.querySelectorAll('[data-follow]').forEach(x=>x.onclick=()=>follow(x.dataset.follow,x.dataset.state==='1'));document.querySelectorAll('[data-friend]').forEach(x=>x.onclick=()=>friend(x.dataset.friend));document.querySelectorAll('[data-ban]').forEach(x=>x.onclick=()=>ban(x.dataset.ban,x.dataset.state==='1'));document.querySelector('#search')?.addEventListener('submit',async e=>{e.preventDefault();try{showProfile((await api(`profile/${encodeURIComponent(new FormData(e.currentTarget).get('username'))}`)))}catch(x){toast(x.message)}})}
async function openTab(t){S.tab=t;if(t==='games'){try{S.games=(await api('games')).games}catch{S.games=[]}renderGames()}else if(t==='mine'){if(!S.user)return auth(false);try{S.mine=(await api('games?mine=1')).games}catch{S.mine=[]}renderMine()}else if(t==='friends'){if(!S.user)return auth(false);renderFriends()}else if(t==='profile'){if(!S.user)return auth(false);try{const d=await api('me');S.user=d.user;S.stats=d.stats}catch{}showProfile({profile:S.user,stats:S.stats})}else if(t==='admin')renderAdmin()}
function renderGames(){layout(`<section class="hero"><div><small>THE SURELIN PLATFORM</small><h1>Play.<br>Create.<br>Share.</h1><p>Discover community games and build your own worlds with a lightweight browser editor.</p><div class="actions"><button class="primary" id="newgame">Create a game →</button><button class="secondary" data-tab="mine">Your Games</button></div></div><div class="hero-art"><div class="core"></div><b>CREATOR MODE</b><span>3D editing · saving · publishing</span></div></section><section class="head"><div><small>DISCOVER</small><h2>Games</h2></div><span>${S.games.length} published</span></section><section class="grid">${S.games.length?S.games.map(card).join(''):`<div class="empty">No published games yet.<br><button class="primary small" id="newgame">Create the first one</button></div>`}</section>`)}
function card(g){const owner=g.profiles?.display_name||g.profiles?.username||'creator';return `<article class="card"><div class="thumb"><div class="cube"></div><em>SURELIN</em></div><div class="ci"><div><h3>${esc(g.name)}</h3><p>${esc(g.description||'A new Surelin world.')}</p></div><label>${g.visibility}</label></div><footer>by @${esc(owner)} <button data-game="${g.id}">Open →</button></footer></article>`}
function renderMine(){layout(`<section class="pagehead"><div><small>CREATOR</small><h1>Your Games</h1><p>Build, save and publish your worlds.</p></div><button class="primary" id="newgame">＋ New game</button></section><section class="grid">${S.mine.length?S.mine.map(card).join(''):`<div class="empty">You haven't created a game yet.</div>`}</section>`)}
function renderFriends(){layout(`<section class="pagehead"><div><small>SOCIAL</small><h1>Friends</h1><p>Connect with other Surelin creators.</p></div></section><section class="cols"><div class="panel"><h2>Friend requests</h2><div id="requests"><div class="empty smallempty">Loading…</div></div></div><div class="panel"><h2>Find a creator</h2><form id="search" class="inline"><input name="username" placeholder="username" autocomplete="off"><button class="secondary">Open profile</button></form><p class="muted">Follow creators or send a friend request from their profile.</p></div></section>`);api('friends').then(d=>{const incoming=d.requests.filter(r=>r.status==='pending'&&r.receiver_id===S.user.id);document.querySelector('#requests').innerHTML=incoming.length?incoming.map(r=>`<div class="row">${av(r.profiles_sender?.username)}<div><b>@${esc(r.profiles_sender?.username)}</b><span>sent you a request</span></div><button class="primary small" data-accept="${r.id}">Accept</button></div>`).join(''):`<div class="empty smallempty">No incoming requests.</div>`;document.querySelectorAll('[data-accept]').forEach(x=>x.onclick=async()=>{try{await api('friends/accept',{method:'POST',body:JSON.stringify({id:x.dataset.accept})});toast('Friend added!',true);renderFriends()}catch(e){toast(e.message)}})}).catch(e=>toast(e.message))}
async function follow(u,following){try{await api(`follow/${encodeURIComponent(u)}`,{method:following?'DELETE':'POST'});showProfile(await api(`profile/${encodeURIComponent(u)}`));toast(following?'Unfollowed':'Following',true)}catch(e){toast(e.message)}}
async function friend(u){try{const d=await api(`friends/${encodeURIComponent(u)}`,{method:'POST'});toast(d.status==='accepted'?'You are friends!':'Friend request sent.',true)}catch(e){toast(e.message)}}
function showProfile(d){const p=d.profile;layout(`<section class="profilehead">${av(p.username)}<div><small>CREATOR PROFILE</small><h1>${esc(p.display_name)}</h1><p>@${esc(p.username)}</p></div>${S.user&&S.user.username!==p.username?`<div class="profilebuttons"><button class="primary small" data-follow="${esc(p.username)}" data-state="${d.relationship?.following?'1':'0'}">${d.relationship?.following?'Following':'Follow'}</button><button class="secondary small" data-friend="${esc(p.username)}">${d.relationship?.friendStatus==='accepted'?'Friends':'Add friend'}</button></div>`:''}</section><div class="stats"><div><b>${d.stats.followers}</b><span>Followers</span></div><div><b>${d.stats.following}</b><span>Following</span></div><div><b>${d.stats.games}</b><span>Games</span></div><div><b>${p.sura}</b><span>Sura</span></div></div><section class="panel"><small>ABOUT</small><p>${esc(p.bio||'No bio yet.')}</p></section>`)}
async function renderAdmin(){if(!S.user?.is_admin)return openTab('games');let o={stats:{users:0,games:0,follows:0,friendLinks:0}},u=[];try{o=await api('admin/overview');u=(await api('admin/users')).users}catch(e){toast(e.message)}layout(`<section class="pagehead"><div><small>CONTROL CENTER</small><h1>Admin</h1><p>Moderation and platform overview.</p></div></section><div class="stats"><div><b>${o.stats.users}</b><span>Users</span></div><div><b>${o.stats.games}</b><span>Games</span></div><div><b>${o.stats.follows}</b><span>Follows</span></div><div><b>${o.stats.friendLinks}</b><span>Friend links</span></div></div><section class="panel"><h2>Users</h2>${u.map(x=>`<div class="row">${av(x.username)}<div><b>@${esc(x.username)}</b><span>${esc(x.display_name)} · ${x.sura} sura</span></div><div><label>${x.is_banned?'banned':'active'}</label>${x.id===S.user.id?'<span class="muted">you</span>':`<button class="danger small" data-ban="${x.id}" data-state="${x.is_banned?'1':'0'}">${x.is_banned?'Unban':'Ban'}</button>`}</div></div>`).join('')}</section>`)}
async function ban(id,banned){try{await api('admin/ban',{method:'POST',body:JSON.stringify({userId:id,banned:!banned})});toast(banned?'Unbanned':'Banned',true);renderAdmin()}catch(e){toast(e.message)}}
function auth(sign){const m=document.createElement('div');m.className='modalwrap';m.innerHTML=`<div class="modal"><button class="x">×</button><small>${sign?'JOIN SURELIN':'WELCOME BACK'}</small><h2>${sign?'Create your account':'Log in'}</h2><p>${sign?'No email. No Discord. Just a Surelin username and password.':'Enter your Surelin credentials.'}</p><form><label>Username<input name="username" required minlength="3" maxlength="20" pattern="[A-Za-z0-9_]+" autocomplete="username"></label>${sign?'<label>Display name<input name="displayName" maxlength="40" placeholder="optional"></label>':''}<label>Password<input type="password" name="password" required minlength="8" autocomplete="current-password"></label><button class="primary full">${sign?'Create account':'Log in'} →</button></form><button class="switch">${sign?'Already have an account? Log in':'Need an account? Create one'}</button></div>`;document.body.append(m);m.querySelector('.x').onclick=()=>m.remove();m.querySelector('.switch').onclick=()=>{m.remove();auth(!sign)};m.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const d=await api(`auth/${sign?'signup':'login'}`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});localStorage.setItem('surelin_token',d.token);S.user=d.user;m.remove();toast(sign?'Welcome to Surelin!':'Welcome back!',true);openTab('games')}catch(x){toast(x.message)}}}

class Editor{
constructor(game){this.game=game;this.objs=[];this.selected=null;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#080b12');this.cam=new THREE.PerspectiveCamera(60,1,.1,1000);this.cam.position.set(7,6,9);this.r=new THREE.WebGLRenderer({antialias:true});this.r.shadowMap.enabled=true;this.r.setPixelRatio(Math.min(devicePixelRatio,2));this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.controls=null}
mount(){document.body.innerHTML=`<div class="editor"><header><button class="brand" id="back"><i>S</i> surelin</button><input id="gname" value="${esc(this.game?.name||'Untitled world')}"><div class="right"><button class="secondary" id="save">Save</button><button class="primary small" id="publish">Publish</button></div></header><aside class="tools"><small>CREATE</small><button data-add="cube">▣ Cube</button><button data-add="sphere">● Sphere</button><button data-add="plane">▱ Plane</button><button data-add="light">☼ Light</button><small>WORLD</small><button id="reset">◎ Reset camera</button></aside><section id="view"></section><aside class="inspector"><small>INSPECTOR</small><div id="insp">Select an object.</div></aside><footer>Orbit: drag · Zoom: scroll · Select: click <span id="status">Ready</span></footer></div>`;const v=document.querySelector('#view');v.append(this.r);this.controls=new OrbitControls(this.cam,this.r.domElement);this.controls.enableDamping=true;this.scene.add(new THREE.HemisphereLight(0xbcc7ff,0x16131f,1.8));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(5,9,4);this.scene.add(dl);this.scene.add(new THREE.GridHelper(30,30,0x34384a,0x1c2030));if(this.game?.scene?.objects?.length)this.load(this.game.scene);else this.add('plane');document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>this.add(x.dataset.add));document.querySelector('#back').onclick=()=>openTab('mine');document.querySelector('#save').onclick=()=>this.save(false);document.querySelector('#publish').onclick=()=>this.save(true);document.querySelector('#reset').onclick=()=>{this.cam.position.set(7,6,9);this.controls.target.set(0,1,0)};this.r.domElement.onpointerdown=e=>this.pick(e);addEventListener('resize',()=>this.resize());this.resize();this.animate()}
resize(){const v=document.querySelector('#view');if(!v)return;const w=v.clientWidth,h=v.clientHeight;this.cam.aspect=w/h;this.cam.updateProjectionMatrix();this.r.setSize(w,h,false)}
add(type,d={}){let o;if(type==='cube')o=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:d.color||0x8066ff,roughness:.7}));if(type==='sphere')o=new THREE.Mesh(new THREE.SphereGeometry(.7,28,18),new THREE.MeshStandardMaterial({color:d.color||0x54d0b8,roughness:.5}));if(type==='plane')o=new THREE.Mesh(new THREE.BoxGeometry(8,.25,8),new THREE.MeshStandardMaterial({color:d.color||0x252a38,roughness:.9}));if(type==='light'){o=new THREE.PointLight(d.color||0xffffff,d.intensity||12,15);o.add(new THREE.Mesh(new THREE.SphereGeometry(.12,12,8),new THREE.MeshBasicMaterial({color:0xffffff})))}o.position.fromArray(d.position||[0,type==='plane'?-0.15:1,0]);o.rotation.fromArray(d.rotation||[0,0,0]);o.scale.fromArray(d.scale||[1,1,1]);o.userData={id:d.id||crypto.randomUUID(),type,name:d.name||type};o.castShadow=true;if(o.isMesh)o.receiveShadow=true;this.scene.add(o);this.objs.push(o);this.select(o)}
select(o){this.selected=o;this.inspect()}
pick(e){const q=this.r.domElement.getBoundingClientRect();this.pointer.x=(e.clientX-q.left)/q.width*2-1;this.pointer.y=-(e.clientY-q.top)/q.height*2+1;this.ray.setFromCamera(this.pointer,this.cam);const h=this.ray.intersectObjects(this.objs,true)[0];if(h){let o=h.object;while(o.parent&&!this.objs.includes(o))o=o.parent;this.select(o)}}
inspect(){const b=document.querySelector('#insp');if(!this.selected){b.textContent='Select an object.';return}const o=this.selected,p=o.position,s=o.scale;b.innerHTML=`<label>Name<input id="oname" value="${esc(o.userData.name)}"></label><b>Position</b><div class="trip"><input id="px" value="${p.x.toFixed(2)}"><input id="py" value="${p.y.toFixed(2)}"><input id="pz" value="${p.z.toFixed(2)}"></div><b>Scale</b><div class="trip"><input id="sx" value="${s.x.toFixed(2)}"><input id="sy" value="${s.y.toFixed(2)}"><input id="sz" value="${s.z.toFixed(2)}"></div><button class="danger full" id="del">Delete object</button>`;b.querySelector('#oname').onchange=e=>o.userData.name=e.target.value;['px','py','pz'].forEach((id,i)=>b.querySelector('#'+id).onchange=e=>o.position.setComponent(i,Number(e.target.value)||0));['sx','sy','sz'].forEach((id,i)=>b.querySelector('#'+id).onchange=e=>o.scale.setComponent(i,Number(e.target.value)||1));b.querySelector('#del').onclick=()=>{this.scene.remove(o);this.objs=this.objs.filter(x=>x!==o);this.selected=null;this.inspect()}}
serialize(){return{version:1,objects:this.objs.map(o=>({id:o.userData.id,type:o.userData.type,name:o.userData.name,position:o.position.toArray(),rotation:[o.rotation.x,o.rotation.y,o.rotation.z],scale:o.scale.toArray(),color:o.material?.color?.getHexString?'#'+o.material.color.getHexString():'#fff'}))}}
load(s){(s.objects||[]).forEach(o=>this.add(o.type,o));this.selected=null;this.inspect()}
async save(pub){try{const payload={name:document.querySelector('#gname').value.trim()||'Untitled world',description:this.game?.description||'',visibility:this.game?.visibility||'private',published:pub||Boolean(this.game?.published),scene:this.serialize()};const d=this.game?.id?await api(`games/${this.game.id}`,{method:'PATCH',body:JSON.stringify(payload)}):await api('games',{method:'POST',body:JSON.stringify(payload)});this.game=d.game;document.querySelector('#status').textContent=pub?'Published':'Saved';toast(pub?'Game published!':'Game saved!',true)}catch(e){toast(e.message)}}
animate(){if(!document.querySelector('.editor'))return;requestAnimationFrame(()=>this.animate());this.controls.update();this.r.render(this.scene,this.cam)}}
function editor(id){if(!S.user)return auth(false);const g=[...S.mine,...S.games].find(x=>x.id===id);if(g&&g.owner_id&&g.owner_id!==S.user.id){toast('You can only edit your own games.');return}new Editor(g).mount()}
async function boot(){if(localStorage.getItem('surelin_token'))try{const d=await api('me');S.user=d.user;S.stats=d.stats}catch{localStorage.removeItem('surelin_token')}openTab('games')}
boot()
